<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logic certus desarrollo de software</title>
    
</head>
<body>
    
    <header>
        <!-- logo,menu,etc-->
        <h1><p style="color:red; font-size:100px">Logiccertus :desarrollo de software </p> </h1>
        <nav>
            <!-- navegacion-->
            <ul>
                 <li><a href="CONOCENOS.html">CONOCENOS</a></li>
                 <li><a href="registrarse.html">registrarse</a></li>
                 <li><a href="VENTAS.html">VENTAS</a></li>
                 <li><a href="SERVICIOS QUE TE PUEDEN BRINDAR NUESTRAS EMPRESAS " target=">blank">SERVICIOS QUE TE PUEDEN BRINDAR NUESTRAS EMPRESAS</a></li>
                 <li><a href="PROYECTOS.html">PROYECTOS</a></li>
                 <li><a href="CLIENTES.html">VENTAS</a></li>
                 <li><a href="CERTIFICACIONES.html">PROYECTOS</a></li>
                 <li><a href="CONTACTOS.html">PROYECTOS</a></li>
            </ul>
        </nav>

    </header>

    <body>
        <h1>Logiccertus</h1>
        <table>
        <tr>
         <th>
        
            nosotros锔锔锔锔锔锔锔锔锔
         </th>
        
        </tr>
        <table>
        <tr>
        
            <dt>
        
                <video controls width="1000px" height="600px"  autoplay>
                    <source src="Espectacular video corporativo para empresa _ DOSIS.mp4"type="video/mp4">
                </video>
            </dt>
        </tr>
        </table>
        
        
            
        </body>
    <nav>

     <!--navegacion-->
    </nav>
    <main>
        <!--la pagina web principal-->
        <section>
        <h2>Como damos conocimiento acerca de servicios que puedan brindar nuestras diferentes empresas ?</h2>
    <article>
            <p>ATRAVES DE: 
                <H3>1.- Redes sociales</H3>
                Para unemprendimiento exitoso, las redes sociales ayudan a dar visibilidad creando una comunidad de personas afines a los valores de marca y, por lo tanto, clientes potenciales.
                No se trata de abrir cuentas en todas las redes. Es mejor enfocarse en dos o tres, pero mantenerlas en constante actividad. La decisi贸n de una red social sobre otra debe basarse en el tipo de personas a las cuales se busca atraer y la clase de producto o servicio que se ofrece. Es decir, si la marca est谩 pensada en un p煤blico joven, Snapchat puede ser una buena opci贸n, por otro lado, si se busca vender servicios a empresas, LinkedIn es ideal.
                A fin de mantener seguidores comprometidos con la marca, podr铆an establecerse algunas estrategias como compartir contenido entretenido y relevante de acuerdo con el p煤blico objetivo. Asimismo, es vital prestar especial atenci贸n a los comentarios de los usuarios, respondiendo dudas de forma amistosa pero profesional.
                <H3>2.- Facebook Ads</H3>
                Los anuncios pagados de Facebook son una valiosa herramienta de publicidad para emprendedores, pues facilita la segmentaci贸n de audiencias mostrando anuncios solamente a usuarios que se identifiquen en alg煤n aspecto con la marca. Es posible seleccionar los perfiles con relaci贸n a caracter铆sticas sociodemogr谩ficas, gustos y preferencias, entre muchas variantes.
                Facebook Ads es bastante econ贸mico comparado con otros medios publicitarios porque solo se genera un cargo cuando el usuario reacciona y da clic. En consecuencia, cuando alguien no entra al enlace, a煤n se est谩 visualizando a la marca sin generar cargos.
                
                <H3>3.- Sitio web y blog de contenidos</H3>
                Un sitio web es importante para las startups reci茅n creadas si se pretende facilitar su posicionamiento, pero incluir un blog agregando contenido actualizado, con palabras clave atractivas al p煤blico, facilita que buscadores como Google lo expongan en las primeras posiciones de resultados.
                Los contenidos son muy valiosos para atraer a clientes potenciales con alguna necesidad, de manera en que la informaci贸n escrita en el blog puede ayudarlos a resolver el problema. De esta forma, la empresa se muestra como referente y experto en su sector, otorgando contenidos 煤tiles y relevantes.
                <H3>4.- Estrategia de prescriptores</H3>
                Las rese帽as y calificaciones de los clientes tienen un gran peso en la decisi贸n de compra, por ello88% de los consumidores se ven influenciados por una rese帽aen el proceso de adquirir un producto. Los esfuerzos deben concentrarse en motivar a los clientes a expresar su experiencia con el prop贸sito de aumentar ventas.
                En primer lugar, la empresa debe darse de alta en sitios donde los consumidores acuden en busca de negocios, por ejemplo, Google Maps, Yelp, Facebook, Bing y Yahoo. Despu茅s, brindar alg煤n incentivo para que un cliente satisfecho comparta su experiencia en estos lugares, como un cup贸n de descuento en la pr贸xima compra o la participaci贸n en un sorteo. Igualmente, se puede enviar un correo de agradecimiento y seguimiento postventa donde se solicite una rese帽a.
                <H3>5.- Google Maps</H3>
                Esta es una herramienta ideal para darse a conocer ante personas con una necesidad a resolver pronto. Al rastrear negocios locales en el navegador de Google, los principales resultados arrojados por la p谩gina son los ofrecidos por Google Maps. En este sentido, no es casual unaumento del 500% en b煤squedasque incluyen la frase "cerca de m铆", muchas de ellas con intenci贸n de compra.
                <H3>6.- Campa帽as de email</H3>
                La publicidad por email ha evolucionado enormemente desde los antiguos correos electr贸nicos de spam, enviados indistintamente a cualquier persona, con mensajes molestos y agresivos invitando a comprar.
                Actualmente, el email es una herramienta indispensable en estrategias como el inbound marketing, el cual, gracias a la segmentaci贸n, permite enviar informaci贸n relevante de acuerdo con las necesidades de cada suscriptor a la lista de correo y su etapa dentro del embudo de ventas. El inbound marketing se encarga de acompa帽ar al cliente potencial, con contenido educativo, con la finalidad de prepararlo para la compra.
                Conseguir clientes es solo el primer paso, ya que es necesario agregar valor en su experiencia con la marca, no solo para tenerlos de vuelta en otra compra, sino con el objetivo de impresionarlos al punto de esperar a sus contactos por medio de recomendaciones.
                Hoy, m谩s que nunca, es posible aumentar clientes utilizando herramientas de promoci贸n gratuitas o al alcance de cualquier presupuesto. En cada una de ellas es importante dirigirse a las personas apropiadas, por medio de mensajes convenientes y cuidar toda interacci贸n con la marca, en vista de ofrecer la mejor experiencia.
                </p>

            <footer>

            <p><img src="lala.jpg" alt<"EMPRESAS"> </p> 
            </footer>
        </article>
         <article>
            <header>

                <h3>COMO GENERAR VALOR?</h3>
            
            </header>
            <p> EL VALOR PRINCIPAL QUE GENERA EL PROYECTO 
                驴Qu茅 GANAMOS DANDO CONOCIMIENTO DE SERVICIOS QUE PUEDAN BRINDAR NUESTRAS EMPRESAS?
                OBTENDREMOS MAS VENTA Y MAS INGRESOS PARA NUESTRAS EMPRESAS EL CUAL NOS FACILITA INVERTIR CAPITAL EN NUESTRAS EMPRESAS
                </p>
            <foooter>

                <p>EL PROYECTO GENERA VALOR EN CADA UNO DE NOSOTROS DE MANERA QUE CADA DIA APRENDEMOS MAS COSAS ACERCA DE LA PROGRAMACION ,LA AGILIDAD,LOS LENGUAJES
                    Y A DEMAS OBTENEMOS INGRESOS GRACIAS CON LA PAGINA YA QUE SE PODRA PUBLICITARLA FACILMENTE</p>
                    
            </foooter>


         </article>
        <article>
            <header>

                <h3> MISION Y VISION</h3>

            </header>

            <p> 
                <H2>VISIN</H2>

                Proporcionar soluciones integrales de ingenier铆a, gestionando, desarrollando, supervisando y ejecutando proyectos de automatizaci贸n, instrumentaci贸n, control de procesos y proyectos electromec谩nicos, por medio de la innovaci贸n, mejora continua y sustentabilidad de nuestros procesos. Contando para ello con personal calificado y experimentado en la aplicaci贸n de soluciones de tipo industrial, utilizando tecnolog铆a de punta para superar las expectativas de nuestros clientes y colaborar con el desarrollo econ贸mico de la regi贸n, asegurando el crecimiento y la rentabilidad para la empresa, los clientes y colaboradores.
                
                 Visi贸n de Seguridad y Medio Ambiente
                
                El compromiso de nuestra empresa es promover la protecci贸n de nuestro mayor recurso que son nuestros trabajadores a trav茅s de la identificaci贸n de peligros y el control de los mismos, as铆 como evitar p茅rdidas, accidentes, enfermedades profesionales, da帽os a la propiedad o al medio ambiente.
                
                <H2>MISION</H2>
                
                 En LOGIC CERTUS, tenemos la Visi贸n de ser la empresa l铆der a nivel nacional, en la venta y desarrollo de soluciones integrales de ingenier铆a, instrumentaci贸n, automatizaci贸n, control de procesos y servicios electromec谩nicos; apoyados en la calidad de nuestros productos, la calidad de nuestros servicios, nuestros valores institucionales, y la excelencia de nuestra gente. <span style="background-color: yellow;">mas<a href="noticia01.html">informaicion</a></span></p>
            <img src="zoom.jpg" alt<"barranco">
        </article>
        </section>
    </main>
    <footer>
       <!--pie de pagina-->
       pie

    </footer>

   
</body>
</html>